name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "**" ]   # runs on feature-branch pushes too
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -q
